[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm start develop"
  targetPort = 4321    
  port = 5432

[functions]
  node_bundler = "esbuild"
  directory = "functions"
  included_files = ["functions/*.handlebars"]
  external_node_modules = [
    "nodemailer",
    "nodemailer-express-handlebars",
    "zod"
  ]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build.environment]
  NODE_VERSION = "21.2.0"